My first pull request uwu
caeres/pomodivity pull request #3
Opened 2021-12-05 13:30 UTC by caeres

2021-12-05 18:05 UTC, CiriousJoker requested changes

2021-12-06 15:02 UTC, caeres commented on index.css
> +  margin: 5px 0;
what

2021-12-06 15:05 UTC, CiriousJoker commented on index.css
> +  margin: 5px 0;
4, 8, 16, 24, 32, 48, 64, 128 are common values for margins and sizes. 24 is usually for fonts and icons, 48 for icons

2021-12-06 15:54 UTC, caeres commented on index.css
> +/* MAIN BODY STYLING */
mach ich ihm nächsten project / sobald eins groß genug ist
spätestens dann fühlt es sich nach nem muss an

2021-12-06 15:56 UTC, caeres commented on index.html
> +    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
wird von bootstrap benötigt (modal) 
damit da alles funktioniert, muss man die drei sachen importieren

2021-12-08 15:18 UTC, merged

2021-12-08 15:18 UTC, caeres commented
ah wait
i forgot the push the changes before lol

2021-12-08 17:01 UTC, CiriousJoker commented
@caeres 
Yeah, also you shouldn't push if the reviewer requested changes. Usually, you push your changes, the reviewer gets notified, reviews them and approves the merge. Then you merge and delete the branch.

2021-12-08 17:02 UTC, CiriousJoker commented
Just create a new one and I'll review that one.